//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
float f_lerp(in float a,in float b, in float t) {
	return a + t * (b - a);
}
//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
vec3 f_lerp(in vec3 a,in vec3 b, in float t) {
	return a + t * (b - a);
}
//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
float f_mapFloat(float from_min, float from_max, float to_min, float to_max, float value) {
	return (to_min + ((to_max - to_min) / (from_max - from_min)) * (value - from_min));
}
//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
float f_mapFloatClamp(float from_min, float from_max, float to_min, float to_max, float value) {
	if (value > from_max) return to_max;
	else if (value < from_min) return to_min;
	else return (to_min + ((to_max - to_min) / (from_max - from_min)) * (value - from_min));
}
//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
vec2 f_mapVec2(vec2 from_min, vec2 from_max, vec2 to_min, vec2 to_max, vec2 value) {
	return vec2(f_mapFloat(from_min.x, from_max.x, to_min.x, to_max.x, value.x), f_mapFloat(from_min.y, from_max.y, to_min.y, to_max.y, value.y));
}
//-------------------------------------------------------------------------------------------------
//-------------------------------------------------------------------------------------------------
mat4 rotateYawPitchRoll(float yaw, float pitch, float roll) {
	mat4 rotationX = mat4(1.0);
	mat4 rotationY = mat4(1.0);
	mat4 rotationZ = mat4(1.0);

	// Yaw (rotation around y-axis)
	rotationY = mat4(
		cos(yaw), 0.0, sin(yaw), 0.0,
		0.0, 1.0, 0.0, 0.0,
		-sin(yaw), 0.0, cos(yaw), 0.0,
		0.0, 0.0, 0.0, 1.0
	);

	// Pitch (rotation around x-axis)
	rotationX = mat4(
		1.0, 0.0, 0.0, 0.0,
		0.0, cos(pitch), -sin(pitch), 0.0,
		0.0, sin(pitch), cos(pitch), 0.0,
		0.0, 0.0, 0.0, 1.0
	);

	// Roll (rotation around z-axis)
	rotationZ = mat4(
		cos(roll), -sin(roll), 0.0, 0.0,
		sin(roll), cos(roll), 0.0, 0.0,
		0.0, 0.0, 1.0, 0.0,
		0.0, 0.0, 0.0, 1.0
	);

	return rotationY * rotationX * rotationZ; // Yaw * Pitch * Roll
}